name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Create tarball
        run: tar czf catppuccin-gitea.tar.gz --directory=./dist .
      - name: Add zips to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./lugit-theme.tar.gz
